package net;

import net.creativetabs.DemonCraftTab;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.common.capabilities.CapabilityManager;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.Event;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.networking.Networking;
import net.proxy.ServerProxy;
import net.util.capabilities.slayer.ISlayerCapability;
import net.util.capabilities.slayer.IStorage;
import net.util.capabilities.slayer.SlayerCapability;
import net.util.capabilities.techniquecapability.ITechStorage;
import net.util.capabilities.techniquecapability.TechCapability;
import net.util.capabilities.techniquecapability.ITechCapability;
import net.util.handlers.Reference;
import net.util.handlers.RenderHandler;
import net.world.Events;
import software.bernie.geckolib3.GeckoLib;

@Mod(modid = Reference.MODID, name = Reference.NAME, version = Reference.VERSION)
public class DemonCraft
{


    public static final CreativeTabs demoncrafttab = new DemonCraftTab("demon_craft_tab");

    @SidedProxy(clientSide = Reference.CLIENT, serverSide = Reference.COMMON)
    public static ServerProxy proxy;


    @Mod.Instance
    public static DemonCraft instance;


    @Mod.EventHandler
    public static void preInit(FMLPreInitializationEvent event) {
        //Sets the information for the mod
        ModMetadata data = event.getModMetadata();
        data.autogenerated = false;
        data.description = "Demon Slayer Mod for the DemonCraft Server";
        data.credits = "Coder/Creator/Modeler:King Typhon , Modeler: Kuro, Owner:Image";
        data.logoFile = "assets/demoncraft/Logo.png";
        data.url = "https://discord.gg/7x6gSwQN6g";


        GeckoLib.initialize();
        //Sends events for things needed to be called before initialization
        CapabilityManager.INSTANCE.register(ISlayerCapability.class, new IStorage(), SlayerCapability::new);
        CapabilityManager.INSTANCE.register(ITechCapability.class, new ITechStorage(), TechCapability::new);
        RenderHandler.registerEntityRenderers();


    }
    @EventHandler
    public static void init(FMLInitializationEvent event) {
        proxy.registerClientStuff();
        Networking.init();


    }
    @EventHandler
    public static void postInit(FMLPostInitializationEvent event) {

    }
    @SubscribeEvent
    static void listen(Event e){

        MinecraftForge.EVENT_BUS.register(new Events());

    }
}
